### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by zoosky** [alexandergall/nixos-cloud-image#1]
I am looking for a way to deploy nixos on Openstack at [cloudscale](https://www.cloudscale.ch). 
What is the status of this repo?

Thanx, Andreas

**Comment by alexandergall** [comment]
The master branch works for NixOS up to 16.09. 17.03 is supported in the `nixos-17.03` branch. That one basically contains the `cloud-init` fixes from https://github.com/NixOS/nixpkgs/pull/23024#event-1091929107. I still need to push a fix for `cloud-utils` and a NixOS module to build the disk image itself.

I'd be interested to know whether you're able to build working images from this repo for your cloud before I create those PRs.
